# Generated by Django 4.0.1 on 2022-01-26 21:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 26, 21, 42, 11, 815903, tzinfo=utc)),
        ),
    ]
